[package]
name = "am-doc"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Anima engine crate: am-doc"

[dependencies]
am-eval.workspace = true
am-format.workspace = true
am-math.workspace = true
am-model.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
