[package]
name = "am-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Anima 引擎命令行工具"

[[bin]]
name = "anima"
path = "src/main.rs"

[dependencies]
am-core = { workspace = true, features = ["gpu"] }
am-format.workspace = true
am-model.workspace = true
serde_json.workspace = true

[dev-dependencies]
tempfile = "3.27.0"
